---

- hosts: k3s_cluster
  any_errors_fatal: true
  gather_facts: yes
  become: yes
  roles:
    - role: k3s/prereq
    - role: k3s/download

- hosts: server
  any_errors_fatal: true
  gather_facts: yes
  become: yes
  serial: 1
  roles:
    - role: k3s/server

- hosts: agent
  any_errors_fatal: true
  gather_facts: yes
  become: yes
  roles:
    - role: k3s/agent
