---

- name: Move downloaded k3s binary into place
  command:
    cmd: mv -f {{ k3s_bin_download_path }} /usr/local/bin/k3s
  changed_when: true
  when: k3s_binary_changed

- name: Ensure that no environment files exist for service k3s-agent
  file:
    path: /etc/systemd/system/k3s-agent.service.env
    state: absent

- name: Copy K3s service file
  register: k3s_agent_service
  template:
    src: "k3s-agent.service.j2"
    dest: "{{ systemd_dir }}/k3s-agent.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s-agent
    daemon_reload: "{{ 'yes' if k3s_agent_service.changed else 'no' }}"
    state: "{{ 'restarted' if k3s_agent_service.changed or k3s_binary_changed else 'started' }}"
    enabled: yes
