---
- name: Restart k3s service
  service:
    name: k3s
    state: restarted
    daemon_reload: true
  listen: restart-k3s-service
  # If the service isn't present yet, this would fail in check mode.
  when: not ansible_check_mode

- name: Restart keepalived service
  service:
    name: keepalived
    state: restarted
    daemon_reload: true
  listen: restart-keepalived-service
  # If the service isn't present yet, this would fail in check mode.
  when: not ansible_check_mode
