---
- name: Restart k3s service
  service:
    name: k3s
    state: restarted
    daemon_reload: true
  listen: restart-k3s-service

- name: Restart keepalived service
  service:
    name: keepalived
    state: restarted
    daemon_reload: true
  listen: restart-keepalived-service
