---
k3s_version: v1.22.3+k3s1
ansible_user: debian

# Directory where the k3s systemd service file will be installed
# systemd_dir: /etc/systemd/system

# If you define multiple servers you should be providing a loadbalanced
# apiserver endpoint to all servers here. This default value is only suitable
# for a non-HA setup, if used in a HA setup, it will not protect you if the
# first node fails.
# Also you should define k3s_token so that servers can talk together securely

apiserver_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
k3s_token: "mysupersecuretoken"

# Enable virtual IP address on server nodes to provide control plane api high availability
# Be sure to update the apiserver_endpoint with a dedicated IP address that is not in use by the cluster
# keepalived_enabled: true

# Provide additional server or agent arguments
# extra_server_args: ""
# extra_agent_args: ""

# If set to true don't disable SELinux
# k3s_selinux_enable: false
