---
k3s_version: v1.22.2+k3s2
ansible_user: debian
systemd_dir: /etc/systemd/system
api_service_ip: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
extra_server_args: ""
extra_agent_args: ""

# Selinux
k3s_selinux_enable: true
k3s_selinux_release: v0.4.latest.1
k3s_selinux_package: k3s-selinux-0.4-1
