---
k3s_version: v1.22.2+k3s2
ansible_user: debian
systemd_dir: /etc/systemd/system

# If you define multiple masters you should be providing a loadbalanced
# apiserver endpoint to all masters here. This default value is only suitable
# for a non-HA setup, if used in a HA setup, it will not protect you if the
# first node fails.
# Also you should define k3s_token so that masters can talk together securely

apiserver_endpoint: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
k3s_token: "mysupersecuretoken"

extra_server_args: ""
extra_agent_args: ""

# Selinux
k3s_selinux_enable: true
k3s_selinux_release: v0.4.latest.1
k3s_selinux_package: k3s-selinux-0.4-1
