---

k3s_version: v1.25.14+k3s1
ansible_user: vagrant

apiserver_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
k3s_token: "mysupersecuretoken"

rt_enabled: true
