---
systemd_dir: "/etc/systemd/system"

# If you define multiple servers you should be providing a loadbalanced
# apiserver endpoint to all servers here.  This default value is only
# suitable for a non-HA setup, if used in a HA setup, it will not protect
# you if the first node fails.
apiserver_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"

extra_agent_args: []
