---
- set_fact:
    output_base_path: "{{ lookup('env', 'OUTPUT_BASE_PATH') | default('/', True) }}"

- name: Install keepalived
  import_tasks: keepalived.yml
  when:
    - keepalived_enabled  # also want to be sure this is the desired configuration

- name: Install k3s
  import_tasks: k3s.yml

- name: Enable realtime
  import_tasks: rt.yml
  when: rt_enabled
