---
- fail:
    msg: "k3s_selinux_enable must be boolean value."
  when: k3s_selinux_enable | type_debug != "bool"

- fail:
    msg: "keepalived_enabled must be boolean value."
  when: keepalived_enabled | type_debug != "bool"

# output_base_path can be used to set a starting directory when the path of output files is relative.
# That is why the default is /.
- set_fact:
    output_base_path: "{{ lookup('env', 'OUTPUT_BASE_PATH') | default('/', True) }}"

- name: Install keepalived
  import_tasks: keepalived.yml
  when:
    - keepalived_enabled  # also want to be sure this is the desired configuration

- name: Install k3s
  import_tasks: k3s.yml

- name: Enable realtime
  import_tasks: rt.yml
  when: rt_enabled
