---

- name: Install keepalived
  import_tasks: keepalived.yml
  when:
    - groups['server'] | length > 1  # Only do this if there is more than one server
    - keepalived_enabled  # also want to be sure this is the desired configuration

- name: Install k3s
  import_tasks: k3s.yml
