---
- name: Determine latest K3s version in channel {{ k3s_release_channel }}
  uri:
    url: "{{ k3s_release_channel_url }}/{{ k3s_release_channel }}"
    follow_redirects: safe
    # Ignore any cached results
    force: true
    return_content: false
  register: uri_k3s_release_channel_url
  when: k3s_version == ''

- set_fact:
    effective_k3s_version: "{{ uri_k3s_release_channel_url.url.split('/')[-1] }}"
  when: uri_k3s_release_channel_url is not skipped

- set_fact:
    effective_k3s_version: "{{ k3s_version }}"
  when: uri_k3s_release_channel_url is skipped

- debug:
    var: effective_k3s_version

- name: Check if k3s binary is present
  stat:
    path: /usr/local/bin/k3s
  register: k3s_bin

- name: K3s version check
  command: /usr/local/bin/k3s --version
  register: ks3_local_version
  changed_when: false
  when: k3s_bin.stat.exists
  check_mode: no

- name: Delete k3s if already present and it is the wrong version
  file:
    path: /usr/local/bin/k3s
    state: absent
  when:
    - k3s_bin.stat.exists
    - ks3_local_version.stdout is defined and (ks3_local_version.stdout.find(effective_k3s_version) == -1)

- name: Check if k3s binary is present
  stat:
    path: /usr/local/bin/k3s
  register: k3s_bin

- name: Download k3s binary x64
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ effective_k3s_version }}/k3s
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ effective_k3s_version }}/sha256sum-amd64.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  when:
    - not k3s_bin.stat.exists
    - ansible_facts.architecture == "x86_64"

- name: Download k3s binary arm64
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ effective_k3s_version }}/k3s-arm64
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ effective_k3s_version }}/sha256sum-arm64.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  when:
    - not k3s_bin.stat.exists
    - ( ansible_facts.architecture is search("arm") and
        ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")

- name: Download k3s binary armhf
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ effective_k3s_version }}/k3s-armhf
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ effective_k3s_version }}/sha256sum-arm.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  when:
    - not k3s_bin.stat.exists
    - ansible_facts.architecture is search("arm")
    - ansible_facts.userspace_bits == "32"
