---
- fail:
    msg: "k3s_selinux_enable must be boolean value."
  when: k3s_selinux_enable | type_debug != "bool"

- import_tasks: selinux.yaml

- import_tasks: rhel.yaml
  when:
    - ansible_os_family in ['RedHat']

- import_tasks: rhel-8.yaml
  when:
    - ansible_os_family in ['RedHat']
    - ansible_distribution_major_version == '8'

- import_tasks: common.yaml
